<a href="https://colab.research.google.com/github/prw09/Numpy/blob/main/Numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Advanced Numpy**

In [49]:
import numpy as np

### Numpy array vs Python lists

In [ ]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

3.2602462768554688


In [ ]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.05193185806274414


In [ ]:
# memory

a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [ ]:
# Normal Indexing

In [ ]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

### Advanced Indexing

In [20]:
# Fancy Indexing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a[[0,2,4],[1]]

array([ 1,  9, 17])

In [18]:
a[:, [0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [23]:
# Boolean Indexing

a = np.random.randint(1, 100, 24).reshape(6, 4)
a

array([[69, 88, 38,  5],
       [54, 62, 54, 29],
       [32, 80, 63, 49],
       [68, 81, 71, 46],
       [60, 31, 82, 92],
       [ 1, 71, 50, 96]])

In [24]:
# Find all numbers greater than 50

a > 50

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [ True, False,  True,  True],
       [False,  True, False,  True]])

In [25]:
a[a>50]

array([69, 88, 54, 62, 54, 80, 63, 68, 81, 71, 60, 82, 92, 71, 96])

In [27]:
a[a%2 == 0]

array([88, 38, 54, 62, 54, 32, 80, 68, 46, 60, 82, 92, 50, 96])

In [28]:
a[(a>50) & (a%2 == 0)]

array([88, 54, 62, 54, 80, 68, 60, 82, 92, 96])

In [30]:
a[a % 7 != 0]

array([69, 88, 38,  5, 54, 62, 54, 29, 32, 80, 68, 81, 71, 46, 60, 31, 82,
       92,  1, 71, 50, 96])

In [31]:
a[~(a % 7 == 0)]

array([69, 88, 38,  5, 54, 62, 54, 29, 32, 80, 68, 81, 71, 46, 60, 31, 82,
       92,  1, 71, 50, 96])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [ ]:
# same shape

In [32]:
# diff shape

In [42]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

# print(a)
# print(b)

print(a + b)

[[0 2 4]
 [3 5 7]]


In [51]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [52]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [50]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [53]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [54]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

### Working with mathematical formulas

In [ ]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(100)

sigmoid(a)

In [55]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [56]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)

mse(actual,predicted)

473.12

In [57]:
# binary cross entropy
np.mean((actual - predicted)**2)

473.12

In [60]:
arr = np.array([1, 2, 3, np.nan, 5, 6])
arr

array([ 1.,  2.,  3., nan,  5.,  6.])

In [61]:
a[~np.isnan(arr)]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 6