### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# **Numpy**

In [1]:
import numpy as np

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating a numpy arr

In [ ]:
# Numpy array
arr = np.array([1,2,3])
arr

In [ ]:
# 2D Numpy array

arr = np.array([[1,2,3], [5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
# 3D Numpy array

arr = np.array([[[1,2,3], [5,6,7]], [[1,2,3], [5,6,7]]])
arr

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [ ]:
# Dtype
# You make array of your choice

arr = np.array([1,2,3], dtype=float)
arr

array([1., 2., 3.])

In [ ]:
arr = np.array([1,2,3], dtype=bool)
arr

array([ True,  True,  True])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(14,)

In [ ]:
# np.arange
# makes a array of given range

arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# with reshape

arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr1.ndim # tells wherther the array is in which dimension

2

In [ ]:
arr1.shape

(4, 4)

In [ ]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# used in deep learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.54743157, 0.23939867, 0.28272511, 0.33978661],
       [0.27382955, 0.09620073, 0.1902321 , 0.79294404],
       [0.71969386, 0.21478453, 0.23344095, 0.93216769]])

In [ ]:
# Linspace
# used for machine learning results plotting

np.linspace(-10,10,10).round(2)

array([-10.  ,  -7.78,  -5.56,  -3.33,  -1.11,   1.11,   3.33,   5.56,
         7.78,  10.  ])

In [ ]:
 # identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4D Array
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# **Array Attributes**

In [ ]:

array_1d = np.arange(10,dtype=np.int32)
array_2d = np.arange(12,dtype=float).reshape(3,4)
array_3d = np.arange(8).reshape(2,2,2)

In [ ]:
# Ndim
array_1d.ndim

1

In [ ]:
array_2d.shape

(3, 4)

In [ ]:
# changing datatype
# astype

array_1d.astype(np.int32)

# here it is converted to int-32

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
array_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### **Array Operations**

In [2]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12, 24).reshape(3,4)

In [ ]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr = np.arange(6).reshape(2, 3).astype(float)
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

In [ ]:
# Vector ops
sqaure_of_arr = arr*arr

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]])

In [ ]:
# Sum of arrays

arr1 + arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
arr1 - arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [ ]:
# Scalar operations

arr1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
arr1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# Relationals operators

arr2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
arr2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

## **Array Functions**

In [3]:
 array1 = np.random.random((3,3))
 array1 = np.round(array1*100)
 array1

array([[37., 48., 15.],
       [ 5., 90.,  5.],
       [97., 25., 71.]])

In [4]:
np.max(array1)

97.0

In [ ]:
np.min(array1)

8.0

In [ ]:
np.prod(array1)

18617195520000.0

In [5]:
#  0 -> col and 1 -> row

np.min(array1, axis=1)

array([15.,  5., 25.])

In [6]:
np.max(array1, axis=0)

array([97., 90., 71.])

In [10]:
np.max(array1, axis=1).round(0)

array([48., 90., 97.])

# **Statistical ops**

In [13]:
np.mean(array1).round(2)

43.67

In [14]:
np.var(array1).round(2)

1106.89

In [15]:
np.median(array1).round(2)

37.0

In [16]:
np.std(array1).round(2)

33.27

In [17]:
# trigonometric func

np.sin(array1)

array([[-0.64353813, -0.76825466,  0.65028784],
       [-0.95892427,  0.89399666, -0.95892427],
       [ 0.37960774, -0.13235175,  0.95105465]])

In [18]:
# Dot product
#

arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12, 24).reshape(4,3)

arr1.dot(arr2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# **Indexing and Slicing**

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1[4]

4

In [24]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2[1,2]

6

In [27]:
a2[1,0]

4

In [28]:
a2[2, 2]

10

In [29]:
a2[1,3]

7

In [30]:
a2[2,0]

8

In [34]:
a1[5:8] = 12
a1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
a1_slice = a1[5:8]
a1_slice

array([12, 12, 12])

In [37]:
a1_slice[2] = 23333

In [38]:
a1_slice

array([   12,    12, 23333])

In [39]:
a1

array([    0,     1,     2,     3,     4,    12,    12, 23333,     8,
           9])

In [40]:
# Priniting the 3d tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
a3[1, 1, 1] # printing 7

7

In [42]:
a3[0, 0, 0] # printing 0

0

In [43]:
a3[1,1,0] # printing 6

6

In [44]:
# Slicing
a1

array([    0,     1,     2,     3,     4,    12,    12, 23333,     8,
           9])

In [45]:
a1[2:5]

array([2, 3, 4])

In [46]:
a1[2:5:2]

array([2, 4])

In [4]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[0, :]

array([0, 1, 2, 3])

In [49]:
a2[1, :]

array([4, 5, 6, 7])

In [52]:
a2[:, 2]

array([ 2,  6, 10])

In [53]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [55]:
a2[1:2, 2:]

array([[6, 7]])

In [56]:
a2[2:, 1:3]

array([[ 9, 10]])

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [7]:
a2[::2, ::2]

array([[ 0,  2],
       [ 8, 10]])

In [16]:
a2[1, ::3]

array([4, 7])

In [10]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [14]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
a3[0,1,:]

array([3, 4, 5])

In [30]:
a3[1,:,1]

array([10, 13, 16])

In [36]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [44]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [45]:
# Transpose

arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
arr.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [49]:
# Ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [51]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
#  Stacking

# Horizontally

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5,a2))


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [54]:
# Vertically

np.vstack((a4,a5,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
# Splitting

np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]